import { notFound } from 'next/navigation';
import { getProduct, getProducts } from '@/lib/sanity';
import { getRelatedProducts } from '@/lib/products';
import { ProductGallery } from '@/components/ProductGallery';
import { AmazonButton } from '@/components/AmazonButton';
import { ProductGrid } from '@/components/ProductGrid';
import { FAQAccordion } from '@/components/FAQAccordion';
export async function generateStaticParams(){return (await getProducts()).map((p)=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:{slug:string}}){const p=await getProduct(params.slug);return {title:p?.seoTitle||p?.name,description:p?.seoDescription||p?.shortDescription};}
export default async function ProductPage({params}:{params:{slug:string}}){const p=await getProduct(params.slug); if(!p) notFound(); const related=getRelatedProducts(p); const specs=Object.entries(p.specifications).filter(([,v])=>v); return <main><section className="product-hero"><ProductGallery product={p}/><div><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><p>{p.shortDescription}</p><ul className="check-list">{p.benefits.slice(0,5).map((b)=><li key={b}>{b}</li>)}</ul>{(p.colors?.length||p.models?.length)?<p><strong>Options:</strong> {[...(p.colors||[]),...(p.models||[])].join(', ')}</p>:null}<AmazonButton product={p}>{p.buttonLabel || 'Buy on Amazon'}</AmazonButton><p className="notice">Purchases are completed securely through Amazon.com.</p></div></section><section><h2>Product Benefits</h2><div className="feature-grid">{p.benefits.map((b)=><div className="feature" key={b}><span>✓</span><h3>{b}</h3></div>)}</div></section>{p.description&&<section><h2>Product Description</h2><p>{p.description}</p></section>}{p.features.length>0&&<section><h2>Features</h2><div className="feature-grid">{p.features.map((f)=><div className="feature" key={f.title}><span>{f.icon||'✦'}</span><h3>{f.title}</h3><p>{f.text}</p></div>)}</div></section>}{specs.length>0&&<section><h2>Specifications</h2><table>{specs.map(([k,v])=><tr key={k}><th>{k}</th><td>{v}</td></tr>)}</table></section>}{p.included.length>0&&<section><h2>What is Included</h2><ul className="check-list">{p.included.map((x)=><li key={x}>{x}</li>)}</ul></section>}{p.instructions.length>0&&<section><h2>How to Use</h2><ol className="steps">{p.instructions.map((x)=><li key={x}>{x}</li>)}</ol></section>}{p.care.length>0&&<section><h2>Care and Cleaning</h2><ul>{p.care.map((x)=><li key={x}>{x}</li>)}</ul></section>}<section><h2>Frequently Asked Questions</h2><FAQAccordion faqs={p.faqs}/></section><section className="support-strip"><h2>Product Support</h2><div className="actions"><a className="btn btn-secondary" href="/support">Download Instructions</a><a className="btn btn-secondary" href="/support">Product Support</a><a className="btn btn-secondary" href="/contact">Contact Us</a><a className="btn btn-secondary" href="/support#warranty">Warranty Information</a></div></section>{related.length>0&&<section><h2>Related Products</h2><ProductGrid products={related}/></section>}<div className="mobile-buy"><AmazonButton product={p}>Buy on Amazon</AmazonButton></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Product',name:p.name,description:p.shortDescription,category:p.category,url:`/products/${p.slug}`,brand:{'@type':'Brand',name:'The Yellow Mango'}})}} /></main>}
